
[package]
edition = "2024"
name = "matrix-qq-bridge-runtime"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
async-broadcast = "0.7.2"
base64 = "0.22.1"
futures-util = "0.3.31"
hostport = "0.4.0"
image = "0.25.6"
itertools = "0.14.0"
napi = { version = "3.0.0", features = ["anyhow", "tokio_rt"] }
napi-derive = "3.0.0"
onebot_v11 = { git = "https://github.com/LaikaBridge/onebotv11_rs.git" }
secrecy = { version = "0.10.3", features = ["serde"] }
serde_json = "1.0.142"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
napi-build = "2"
